This notebook performs the following tasks:

3.1 [Explore features](#3.1)


3.2 [Build classifier](#3.2)

Kush did tasks 3.1-3.2. 

In [7]:
# Data tools
import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter

# ML tools
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix

# 3.1 Explore features
<a id='3.1'></a>

In [8]:
train = pd.read_csv('data_train_clean1.csv')
test = pd.read_csv('data_test_clean1.csv')

In [3]:
n = 50000
data_sample = train.sample(n=n)

In [4]:
confusion_matrix(data_sample['Site Permit'], data_sample['Issued or not'])

array([[ 3205, 45420],
       [  560,   815]], dtype=int64)

In [5]:
confusion_matrix(data_sample['Structural Notification'], data_sample['Issued or not'])

array([[ 3322, 44943],
       [  443,  1292]], dtype=int64)

In [6]:
confusion_matrix(data_sample['Fire Only Permit'], data_sample['Issued or not'])

array([[ 3620, 41604],
       [  145,  4631]], dtype=int64)

In [ ]:
permit_type = np.array(pd.get_dummies(data_sample['Permit Type']))
